language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode8.3
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

r_github_packages:
  - jimhester/covr

addons:
  apt:
    packages:
    - libapparmor-dev

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov(type = "examples")'; fi
