language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
